DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS bird;
DROP TABLE IF EXISTS sighting;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE bird (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  common_name TEXT NOT NULL,
  info_url TEXT,
  picture_url TEXT
);

CREATE TABLE sighting (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  bird_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  log_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  notes TEXT,
  FOREIGN KEY (bird_id) REFERENCES bird(id),
  FOREIGN KEY (user_id) REFERENCES user(id)
);